receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "[::]:4317"
      http:
        endpoint: "[::]:4318"
exporters:
  prometheus:
    endpoint: "[::]:9464"
    resource_to_telemetry_conversion:
      enabled: true
  otlphttp:
    endpoint: "http://${TEMPO_PRIVATE_DOMAIN}:4318"
  # loki:
    # endpoint: "http://${LOKI_PRIVATE_DOMAIN}:3100/loki/api/v1/push"
    # labels:
    #   service: "${RAILWAY_SERVICE_NAME}"
processors:
  batch:
  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["worker"], resource.attributes["worker"])
          - set(attributes["service_instance_id"], resource.attributes["service.instance.id"])
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch, transform]
      exporters: [prometheus]
    # logs:
    #   receivers: [otlp]
    #   exporters: [loki]
