receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "[::]:4317"
      http:
        endpoint: "[::]:4318"
exporters:
  prometheus:
    endpoint: "[::]:9464"
  otlphttp:
    endpoint: "http://${TEMPO_PRIVATE_DOMAIN}:4318"
  # loki:
    # endpoint: "http://${LOKI_PRIVATE_DOMAIN}:3100/loki/api/v1/push"
    # labels:
    #   service: "${RAILWAY_SERVICE_NAME}"
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    # logs:
    #   receivers: [otlp]
    #   exporters: [loki]
