receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"
  otlp:
    endpoint: "${TEMPO_PRIVATE_DOMAIN}:3200"
    insecure: true
  # loki:
    # endpoint: "http://${LOKI_PRIVATE_DOMAIN}:3100/loki/api/v1/push"
    # labels:
    #   service: "${RAILWAY_SERVICE_NAME}"
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    # logs:
    #   receivers: [otlp]
    #   exporters: [loki]
